image_text_dataset:
    metadata_path: "/datasets/pracegover/pracegover_173k/pracegover_dataset.json"
    base_image_path: "/datasets/pracegover/images"

    train_set_size: 0.75

    text_column: "comment"
    image_path_column: image_name

    batch_size: 32
    padding_size : 95

model:
    optimizer: "Adam"
    learning_rate: 1e-5
    eps: 1e-6
    weight_decay: 0.001
    betas: [0.9, 0.98]
    scheduler_patience: 10 # steps
    batch_size: 32
    accumulate_grad_batches: 16

trainer:
    accelerator: "gpu"
    max_epochs: 10  # 
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/loss"
    dirpath: "../checkpoints/clip_pt/pretraining_grad_accum"

early_stopping:
    verbose: true
    monitor: "val/loss"
    patience: 100
