cifar10_classes = [
    'avião',
    'automóveis',
    'pássaro',
    'gato',
    'veado',
    'cão',
    'sapo',
    'cavalo',
    'navio',
    'caminhão'
]

cifar10_templates = [
    "uma foto de um {}.",
    "uma foto borrada de um {}.",
    "uma foto em preto e branco de um {}.",
    "uma foto de baixo contraste de um {}.",
    "uma foto de alto contraste de um {}.",
    "uma foto ruim de um {}.",
    "uma boa foto de um {}.",
    "uma foto de um pequeno {}.",
    "Uma foto de um grande {}.",
    "uma foto do {}.",
    "uma foto borrada do {}.",
    "uma foto em preto e branco do {}.",
    "uma foto de baixo contraste do {}.",
    "uma foto de alto contraste do {}.",
    "uma foto ruim do {}.",
    "uma boa foto do {}.",
    "uma foto do pequeno {}.",
    "uma foto do grande {}.",
]

cifar100_classes = [
    'chimpanzé',
    'truta',
    'gambá',
    'aranha',
    'cadeira',
    'tanque',
    'teclado',
    'homem',
    'baleia',
    'lagosta',
    'casa',
    'escaravelho',
    'urso',
    'soricidae',
    'frasco',
    'xícara',
    'ônibus',
    'laranja',
    'mar',
    'carvalho',
    'cama',
    'tulipa',
    'coelho',
    'arranha-céus',
    'maçã',
    'árvore de arce',
    'pinheiro',
    'caracol',
    'pera',
    'ponte',
    'trem',
    'montanha',
    'lagarta',
    'crocodilo',
    'cobra',
    'canguru',
    'golfinho',
    'bovinos',
    'guaxinim',
    'cogumelo',
    'hamster',
    'tigela',
    'lâmpada',
    'foguete',
    'caminhão de recolha',
    'lobo',
    'verme',
    'lontra',
    'girassol',
    'leopardo',
    'raio',
    'cortadora de grama',
    'motocicleta',
    'menino',
    'raposa',
    'palmeira',
    'nuvem',
    'dinossauro',
    'tartaruga',
    'floresta',
    'sofá',
    'papoula',
    'rosa',
    'abelhas',
    'menina',
    'relógio',
    'lata',
    'mesa',
    'estrada',
    'orquídeas',
    'trailer',
    'esquilo',
    'caranguejo',
    'borboleta',
    'trator',
    'castor',
    'salgueiro',
    'camelo',
    'campo',
    'rato',
    'elefante',
    'peixe linguado',
    'pimentão',
    'placa',
    'televisão',
    'peixes de aquário',
    'guarda-roupa',
    'selo',
    'lagarto',
    'baratas',
    'porco-espino',
    'mulher',
    'opossum',
    'bebê',
    'tigre',
    'telefone',
    'tubarão',
    'leão',
    'castelo',
    'bicicleta'
]


cifar100_templates = [
    "uma foto de um {}.",
    "uma foto borrada de um {}.",
    "uma foto em preto e branco de um {}.",
    "uma foto de baixo contraste de um {}.",
    "uma foto de alto contraste de um {}.",
    "uma foto ruim de um {}.",
    "uma boa foto de um {}.",
    "uma foto de um pequeno {}.",
    "Uma foto de um grande {}.",
    "uma foto do {}.",
    "uma foto borrada do {}.",
    "uma foto em preto e branco do {}.",
    "uma foto de baixo contraste do {}.",
    "uma foto de alto contraste do {}.",
    "uma foto ruim do {}.",
    "uma boa foto do {}.",
    "uma foto do pequeno {}.",
    "uma foto do grande {}.",
]


caltech101_classes = [
    "acordeão",
    "avião",
    "âncora",
    "formiga",
    "fundo",
    "barril",
    "baixo",
    "castor",
    "binóculo",
    "bonsai",
    "cérebro",
    "brontossauro",
    "buda",
    "borboleta",
    "câmera",
    "canhão",
    "lado de um carro",
    "ventilador de teto",
    "celular",
    "cadeira",
    "lustre",
    "corpo de uma onça-parda",
    "rosto de um onça-parda",
    "caranguejo",
    "lagostim",
    "crocodilo",
    "cabeça de um crocodilo",
    "xícara",
    "dálmata",
    "nota de dólar",
    "golfinho",
    "libélula",
    "guitarra elétrica",
    "elefante",
    "emu",
    "eufónio",
    "jarro",
    "rosto centrado",
    "rosto não centrado",
    "balsa",
    "flamingo",
    "cabeça de um flamingo",
    "garfield",
    "gazela-girafa",
    "gramófone",
    "piano de cauda",
    "tartaruga",
    "fone de ouvido",
    "ouriço",
    "helicóptero",
    "Ibis",
    "patins",
    "árvore Joshua",
    "canguru",
    "veleiro",
    "lâmpada",
    "laptop",
    "leopardo",
    "Lama",
    "lagosta",
    "lótus",
    "mandolina",
    "efemerópteros",
    "menorá",
    "metrónomo",
    "minareto",
    "motocicleta",
    "nautilus",
    "polvo",
    "ocapi",
    "pagode",
    "panda",
    "pombo",
    "pizza",
    "ornitorrinco",
    "pirâmide",
    "revólver",
    "rinoceronte",
    "galo",
    "saxofone",
    "velha-de-escócia",
    "tesouras",
    "escorpião",
    "cavalo de mar",
    "snoopy",
    "bola de futebol",
    "grampeador",
    "estrelas de mar",
    "estegossauros",
    "sinal de parada",
    "morango",
    "girassol",
    "carrapato",
    "trilobita",
    "guarda-chuva",
    "relógio",
    "nenúfar",
    "cadeira de rodas",
    "gato selvagem",
    "cadeira windsor",
    "chave inglesa",
    "símbolo yin e yang",
]

caltech101_templates = [
    "uma foto de um {}.",
    "uma pintura de um {}.",
    "um plástico {}.",
    "uma escultura de um {}.",
    "um esboço de um {}.",
    "uma tatuagem de um {}.",
    "um brinquedo {}.",
    "uma rendição de um {}.",
    "um bordado {}.",
    "um desenho animado {}.",
    "um {} num jogo de vídeo.",
    "Uma pelúcia de um {}.",
    "um origami de um {}.",
    "arte de um {}.",
    "graffiti de um {}.",
    "um desenho de um {}.",
    "Um rabisco de um {}.",
    "uma foto do {}.",
    "uma pintura do {}.",
    "o plástico {}.",
    "uma escultura do {}.",
    "um esboço do {}.",
    "uma tatuagem do {}.",
    "O brinquedo {}.",
    "uma rendição do {}.",
    "Um bordado de um {}.",
    "o desenho animado do {}.",
    "o {} num jogo de vídeo.",
    "A mais-valia {}.",
    "O origami de um {}.",
    "A arte do {}.",
    "Graffiti do {}.",
    "um desenho do {}.",
    "um esboço do {}.",
]

country211_classes = [
    "Andorra",
    "Emirados Árabes Unidos",
    "Afeganistão",
    "Antígua e Barbuda",
    "Anguila",
    "Albânia",
    "Arménia",
    "Angola",
    "Antártida",
    "Argentina",
    "Áustria",
    "Austrália",
    "Aruba",
    "Ilhas Aland",
    "Azerbaijão",
    "Bósnia-Herzegovina",
    "Barbados",
    "Bangladesh",
    "Bélgica",
    "Burkina Faso",
    "Bulgária",
    "Bahrein",
    "Benim",
    "Bermudas",
    "Brunei Darussalam",
    "Bolívia",
    "Bonaire, São Eustácio e Saba",
    "Brasil",
    "Bahamas",
    "Butão",
    "Botsuana",
    "Bielorrússia",
    "Belize",
    "Canadá",
    "RD Congo",
    "República Centro-Africana",
    "Suíça",
    "Costa do Marfim",
    "Ilhas Cook",
    "Chile",
    "Camarões",
    "China",
    "Colômbia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curaçao",
    "Chipre",
    "República Checa",
    "Alemanha",
    "Dinamarca",
    "Dominica",
    "República Dominicana",
    "Argélia",
    "Equador",
    "Estónia",
    "Egito",
    "Espanha",
    "Etiópia",
    "Finlândia",
    "Fiji",
    "Ilhas Falkland",
    "Ilhas Feroe",
    "França",
    "Gabão",
    "Reino Unido",
    "Granada",
    "Geórgia",
    "Guiana Francesa",
    "Guernsey",
    "Gana",
    "Gibraltar",
    "Gronelândia",
    "Gâmbia",
    "Guadalupe",
    "Grécia",
    "Geórgia do Sul e Sandwich do Sul",
    "Guatemala",
    "Guam",
    "Guiana",
    "Hong Kong",
    "Honduras",
    "Croácia",
    "Haiti",
    "Hungria",
    "Indonésia",
    "Irlanda",
    "Israel",
    "Ilha de Man",
    "Índia",
    "Iraque",
    "Irão",
    "Islândia",
    "Itália",
    "Jersey",
    "Jamaica",
    "Jordânia",
    "Japão",
    "Quênia",
    "República do Quirguizistão",
    "Camboja",
    "São Cristóvão e Nevis",
    "Coreia do Norte",
    "Coreia do Sul",
    "Kuwait",
    "Ilhas Caimão",
    "Cazaquistão",
    "Laos",
    "Líbano",
    "Santa Lúcia",
    "Liechtenstein",
    "Sri Lanka",
    "Libéria",
    "Lituânia",
    "Luxemburgo",
    "Letónia",
    "Líbia",
    "Marrocos",
    "Mónaco",
    "Moldávia",
    "Montenegro",
    "Saint-Martin",
    "Madagáscar",
    "Macedónia",
    "Mali",
    "Mianmar",
    "Mongólia",
    "Macau",
    "Martinica",
    "Mauritânia",
    "Malta",
    "Maurícia",
    "Maldivas",
    "Malaui",
    "México",
    "Malásia",
    "Moçambique",
    "Namíbia",
    "Nova Caledônia",
    "Nigéria",
    "Nicarágua",
    "Países Baixos",
    "Noruega",
    "Nepal",
    "Nova Zelândia",
    "Omã",
    "Panamá",
    "Peru",
    "Polinésia Francesa",
    "Papua-Nova Guiné",
    "Filipinas",
    "Paquistão",
    "Polónia",
    "Porto Rico",
    "Palestina",
    "Portugal",
    "Palau",
    "Paraguai",
    "Catar",
    "Reunião",
    "Roménia",
    "Sérvia",
    "Rússia",
    "Ruanda",
    "Arábia Saudita",
    "Ilhas Salomão",
    "Seychelles",
    "Sudão",
    "Suécia",
    "Cingapura",
    "Santa Elena",
    "Eslovénia",
    "Ilhas Svalbard e Jan Mayen",
    "Eslováquia",
    "Serra Leoa",
    "São Marinho",
    "Senegal",
    "Somália",
    "Sudão do Sul",
    "El Salvador",
    "Sint Maarten",
    "Síria",
    "Eswatini",
    "Togo",
    "Tailândia",
    "Tajiquistão",
    "Timor-Leste",
    "Turquemenistão",
    "Tunísia",
    "Tonga",
    "Turquia",
    "Trindade e Tobago",
    "Taiwan",
    "Tanzânia",
    "Ucrânia",
    "Uganda",
    "Estados Unidos",
    "Uruguai",
    "Usbequistão",
    "Vaticano",
    "Venezuela",
    "Ilhas Vírgenes Britânicas",
    "Ilhas Vírgenes dos Estados Unidos",
    "Vietnã",
    "Vanuatu",
    "Samoa",
    "Kosovo",
    "Iêmen",
    "África do Sul",
    "Zâmbia",
    "Zimbabué",
]

country211_templates = [
    "Uma foto que tirei em {}",
    "Uma foto que tirei durante a visita em {}",
    "Uma foto do meu país de origem {}.",
    "Uma foto da minha visita a {}.",
    "Uma foto que mostra o país de {}."
]


describabletextures_classes = [
    "faixas",
    "manchado",
    "trançados",
    "borbulhado",
    "protuberância",
    "xadrez",
    "teia de aranha",
    "rachaduras",
    "hachurado",
    "cristal",
    "pontilhado",
    "Fibrosas",
    "salpicado",
    "sardento",
    "babado",
    "transparente",
    "grelha",
    "entalhado",
    "favo de mel",
    "entrelaçados",
    "tricotado",
    "rendado",
    "alinhado",
    "marmoreado",
    "emaranhado",
    "malha",
    "paisley",
    "perfurado",
    "erodido",
    "plissado",
    "pontilhados em polka",
    "poroso",
    "esburacado",
    "escamoso",
    "besuntado",
    "em espiral",
    "aspergidos",
    "sujo",
    "estratificados",
    "listrado",
    "tachinhas de metal",
    "enrolado",
    "venosas",
    "waffles",
    "tecido",
    "enrugado",
    "ziguezagueado",
]


describabletextures_templates = [
    "uma foto de uma textura de {}.",
    "uma foto de um padrão de {}.",
    "uma foto de uma coisa no formato de {}.",
    "uma foto de um objeto no formato de {}.",
    "uma foto da textura {}.",
    "uma foto do padrão {}.",
    "uma foto da coisa {}.",
    "uma foto do objeto {}.",
]


eurosat_classes = [
    "terras agrícolas anuais",
    "floresta",
    "escova ou matagal",
    "rodovia ou estrada",
    "Imóveis industriais ou Imóveis comerciais",
    "Prados de pastagens",
    "terras de cultivo permanentes",
    "edifícios residenciais ou casas ou apartamentos",
    "rio",
    "lago ou mar",
]


eurosat_templates = [
    "uma foto de satélite centralizada de {}.",
    "uma foto de satélite centrada de um {}.",
    "uma foto de satélite centralizada do {}.",
]


fgvcaircraft_classes = [
    '707-320',
    '727-200',
    '737-200',
    '737-300',
    '737-400',
    '737-500',
    '737-600',
    '737-700',
    '737-800',
    '737-900',
    '747-100',
    '747-200',
    '747-300',
    '747-400',
    '757-200',
    '757-300',
    '767-200',
    '767-300',
    '767-400',
    '777-200',
    '777-300',
    'A300B4',
    'A310',
    'A318',
    'A319',
    'A320',
    'A321',
    'A330-200',
    'A330-300',
    'A340-200',
    'A340-300',
    'A340-500',
    'A340-600',
    'A380',
    'An-12',
    'ATR-42',
    'ATR-72',
    'BAE 146-200',
    'BAE 146-300',
    'BAE-125',
    'Beechcraft 1900',
    'Boeing 717',
    'C-130',
    'C-47',
    'Cessna 172',
    'Cessna 208',
    'Cessna 525',
    'Cessna 560',
    'Challenger 600',
    'CRJ-200',
    'CRJ-700',
    'CRJ-900',
    'DC-10',
    'DC-3',
    'DC-6',
    'DC-8',
    'DC-9-30',
    'DH-82',
    'DHC-1',
    'DHC-6',
    'DHC-8-100',
    'DHC-8-300',
    'Dornier 328',
    'DR-400',
    'E-170',
    'E-190',
    'E-195',
    'EMB-120',
    'Embraer Legacy 600',
    'ERJ 135',
    'ERJ 145',
    'Eurofighter Typhoon',
    'F-16A-B',
    'F-A-18',
    'Falcon 2000',
    'Falcon 900',
    'Fokker 100',
    'Fokker 50',
    'Fokker 70',
    'Global Express',
    'Gulfstream IV',
    'Gulfstream V',
    'Hawk T1',
    'Il-76',
    'L-1011',
    'MD-11',
    'MD-80',
    'MD-87',
    'MD-90',
    'Metroliner',
    'Model B200',
    'PA-28',
    'Saab 2000',
    'Saab 340',
    'Spitfire',
    'SR-20',
    'Tornado',
    'Tu-134',
    'Tu-154',
    'Yak-42',
]

fgvcaircraft_templates = [
    "Uma foto de um {}, um tipo de aeronave.",
    "Uma foto do {}, um tipo de aeronave."
]

facialemotionrecognition2013_classes = [
    ['nervoso'],
    ['com nojo'],
    ['com medo'],
    ['feliz', 'sorrindo'],
    ['neutro', 'entediado'],
    ['triste', 'depressivo'],
    ['surpreso', 'chocado', 'assustado'],
]


facialemotionrecognition2013_templates = [
    "uma foto de um rosto {}",
    "uma foto de um rosto mostrando a emoção: {}.",
    "uma foto de um rosto que parece estar {}.",
    "Um rosto que parece {}.",
    "Eles parecem {}.",
    "Olha o quão {} eles estão."
]


flowers102_classes = [
    "prímula rosa",
    "orquídea sapatinho",
    "flor de sino",
    "ervilha doce",
    "margarida inglesa",
    "lírio tigre",
    "orquídea borboleta",
    "ave do paraíso",
    "acônito",
    "globethistle pálido",
    "boca-de-leão",
    "tussilagem",
    "protea",
    "cardo de espinho",
    "iris amarelo",
    "flor de globo",
    "flor de cone roxa",
    "Astromélia",
    "campainha da China",
    "copo de leite",
    "lírio laranja",
    "Scabiosa japonica",
    "Fritillaria",
    "Alpínia",
    "Muscari",
    "papoula",
    "Bredo-vermelho",
    "Gentiana acaulis",
    "Alcachofa",
    "Cravina Barbatus",
    "cravo",
    "Flox perene",
    "dama-entre-verdes",
    "Cosmos",
    "azevinho do mar alpino",
    "ruby-lipped cattleya",
    "Flor de capa",
    "Astrantia",
    "Açafrão da conchinchina",
    "Heléboro",
    "gérbera",
    "narciso",
    "Gladíolo",
    "Poinsétia",
    "Lisianthus",
    "Erysimum",
    "margarida",
    "Ranúnculos",
    "Bem-me-quer",
    "dente de leão comum",
    "Petúnia",
    "Amor-perfeito",
    "Prímula",
    "girassol",
    "Sardinheiras",
    "Dália",
    "gaura",
    "gerânio",
    "Dália laranja",
    "Dália cor-de-rosa e amarela",
    "Cautleya spicata",
    "Anêmona-do-japão",
    "Margarida-amarela",
    "Corriola",
    "Papoula californiana",
    "margarida-do-cabo",
    "Açafrão-da-primavera",
    "Iris Germanica",
    "Anêmona",
    "Romneya",
    "Gazânia",
    "Azaléia",
    "lírio de água",
    "rosa",
    "Figueira-Do-Inferno",
    "Glória da manhã",
    "Passiflora",
    "lótus",
    "Tricyrtis",
    "Antúrio",
    "Plumeria",
    "clematis",
    "hibisco",
    "Aquilégia",
    "Rosa do deserto",
    "Lavatera arborea",
    "Magnolia",
    "Ciclamen",
    "Agrião",
    "Canna Lily Pretoria",
    "hippeastrum",
    "Monarda",
    "Tillandsia",
    "Dedaleira",
    "Flor primavera",
    "Camélia",
    "Malva",
    "Petunia mexicana",
    "Bromélia",
    "Gailárdia",
    "Trombeta Americana",
    "Flor-leopardo",
]


flowers102_templates = [
    "uma foto de uma {}, um tipo de flor.",
]


food101_classes = [
    "torta de maçã",
    "costelas baby back ribs",
    "baklava",
    "carpaccio de carne de bovino",
    "tartare de carne de bovino",
    "salada de beterraba",
    "beignet",
    "bibimbap",
    "pudim de pão",
    "café da manhã burrito",
    "bruschetta",
    "salada caesar",
    "cannoli",
    "salada caprese",
    "bolo de cenoura",
    "ceviche",
    "cheesecake",
    "prato de queijo",
    "curry de frango",
    "quesadilla de frango",
    "asas de frango",
    "bolo de chocolate",
    "mousse de chocolate",
    "churros",
    "sopa de amêijoa",
    "sanduíche",
    "bolinho de siri",
    "creme brulee",
    "croque madame",
    "bolos de caneca",
    "ovos cozidos",
    "donuts",
    "bolinhos",
    "edamame",
    "ovos beneditinos",
    "escargots",
    "faláfel",
    "filé mignon",
    "peixes e batatas fritas",
    "foie gras",
    "batatas fritas",
    "sopa de cebola francesa",
    "torradas francesas",
    "lula fritos",
    "arroz frito",
    "iogurte congelado",
    "pão de alho",
    "nhoque",
    "salada grega",
    "sanduíche de queijo grelhado",
    "salmão grelhado",
    "guacamole",
    "gioza",
    "hambúrguer",
    "sopa quente e azeda",
    "cachorro-quente",
    "huevos rancheros",
    "hummus",
    "sorvete",
    "lasanha",
    "bisque de lagosta",
    "sanduíche de lagosta",
    "macarrão e queijo",
    "macarrão",
    "sopa de miso",
    "mexilhões",
    "nachos",
    "omelete",
    "anéis de cebola",
    "ostras",
    "pad tailandesa",
    "Paella",
    "panquecas",
    "panna cotta",
    "pato à pequim",
    "pho",
    "pizza",
    "costeleta de porco",
    "poutine",
    "costela de primeira qualidade",
    "sanduíche de porco puxada",
    "ramen",
    "ravioli",
    "bolo de red velvet",
    "risoto",
    "samosa",
    "sashimi",
    "vieiras",
    "salada de algas marinhas",
    "camarão e grãos",
    "espaguete bolonês",
    "espaguete carbonara",
    "rolinho primavera",
    "bife",
    "bolo de morango",
    "sushi",
    "takoyaki",
    "tiramisú",
    "tartar de atum",
    "waffles",
]


food101_templates = [
    "uma foto de um {}, um tipo de alimento.",
]


gtsrb_classes = [
    "círculo vermelho e branco limite de velocidade de 20 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 30 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 50 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 60 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 70 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 80 quilômetros por hora",
    "fim desrestrição do limite de velocidade de 80 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 100 quilômetros por hora",
    "círculo vermelho e branco limite de velocidade de 120 quilômetros por hora",
    "círculo vermelho e branco carro vermelho e carro preto proibido ultrapassagem",
    "círculo vermelho e branco caminhão vermelho e carro preto proibido ultrapassagem",
    "Alerta de intersecção rodoviária triângulo vermelho e branco",
    "estrada de prioridade diamante branco e amarelo",
    "triângulo vermelho e branco de cabeça para baixo dê a preferência",
    "parar",
    "círculo vermelho e branco vazio",
    "círculo vermelho e branco proibida entrada de caminhão",
    "círculo vermelho com faixa horizontal branca proibida entrada",
    "triângulo vermelho e branco com marca de exclamação de aviso",
    "triângulo vermelho e branco com curva preta para a esquerda aviso de curva à esquerda se aproximando",
    "triângulo vermelho e branco com curva preta para a direita aviso de curva à esquerda se aproximando",
    "triângulo vermelho e branco com curva dupla preta aviso de curva dupla se aproximando",
    "triângulo vermelho e branco aviso de estrada irregular / acidentada",
    "triângulo vermelho e branco carro aviso de derrapagem / deslizamento",
    "triângulo vermelho e branco aviso de mesclagem de ruas / ruas estreitas ",
    "triângulo vermelho e branco com pessoa cavando / construção / aviso de trabalho de estrada",
    "triângulo vermelho e branco sinal de semáforo se aproximando próximo",
    "triângulo vermelho e branco com aviso de pessoa caminhando",
    "triângulo vermelho e branco com aviso de criança e pessoa caminhando",
    "triângulo vermelho e branco com aviso de bicicletas",
    "triângulo vermelho e branco com aviso de neve / gelo",
    "triângulo vermelho e branco com aviso de veado",
    "círculo branco com barra cinza sem limite de velocidade",
    "círculo azul com seta direita branca virada obrigatória",
    "círculo azul com seta esquerda branca virada obrigatória",
    "círculo azul com seta para a frente branca obrigatória",
    "círculo azul com seta branca frente ou direita virada obrigatória",
    "círculo azul com seta branca frente ou esquerda virada obrigatória",
    "círculo azul com seta branca se mantenha à direita",
    "círculo azul com seta branca se mantenha à esquerda",
    "círculo azul com setas brancas indicando um círculo de tráfego",
    "círculo branco com barra cinza indicando nenhuma passagem para carros",
    "círculo branco com barra cinza indicando nenhuma passagem para caminhões",
]


gtsrb_templates = [
    "um zoom na foto de um sinal de trânsito {}.",
    "uma foto centrada de um sinal de trânsito {}.",
    "Uma foto de perto de um sinal de trânsito {}.",
]


hatefulmemes_classes = [
    "meme",
    "meme com discurso de ódio",
]


hatefulmemes_templates = [
    "Um {}.",
]


kitti_classes = [
    "uma foto que tirei de um carro do meu lado esquerdo ou direito.",
    "uma foto que tirei com um carro por perto.",
    "uma foto que tirei com um carro à distância.",
    "uma foto que tirei com nenhum carro.",
]


kitti_templates = [
    "{}",
]


mnist_classes = [
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
]


mnist_templates = [
    "uma foto do número: {}.",
]


oxfordpets_classes = [
    "Abissínio",
    "Buldogue Americano",
    "American pit bull terrier",
    "Basset hound",
    "Beagle",
    "Bengala",
    "Sagrado da Birmânia",
    "Bombaim",
    "Boxer",
    "British Shorthair",
    "Chihuahua",
    "Mau egípcio",
    "Cocker spaniel inglês",
    "Setter inglês",
    "Braco alemão de pelo curto",
    "Cão de montanha dos Pirenéus",
    "Bichon Havanês",
    "Spaniel japonês",
    "keeshond",
    "Leonberger",
    "Maine Coon",
    "Pinscher miniatura",
    "Terra Nova",
    "Persa",
    "Lulu da Pomerânia",
    "Pug",
    "Ragdoll",
    "Azul Russo",
    "São-bernardo",
    "Samoieda",
    "Terrier escocês",
    "Shiba inu",
    "Siamês",
    "Sphynx",
    "Staffordshire bull terrier",
    "Wheaten terrier",
    "Yorkshire terrier",
]


oxfordpets_templates = [
    "uma foto de um {}, um tipo de animal de estimação.",
]


patchcamelyon_classes = [
    "nódulos linfáticos",
    "linfonodo contendo tecido tumoral metastático",
]


patchcamelyon_templates = [
    "esta é uma foto de um {}",
]


resisc45_classes = [
    "avião",
    "aeroporto",
    "campo de beisebol",
    "quadra de basquetebol",
    "praia",
    "ponte",
    "chaparral",
    "igreja",
    "terras agrícolas circulares",
    "nuvem",
    "área comercial",
    "denso residencial",
    "deserto",
    "floresta",
    "auto-estrada",
    "campo de golfe",
    "campo de trilha terrestre",
    "porto",
    "área industrial",
    "intersecção",
    "ilha",
    "lago",
    "prado",
    "área residencial",
    "parque de casa móvel",
    "montanha",
    "passagem",
    "palácio",
    "estacionamento",
    "ferroviário",
    "estação ferroviária",
    "terras agrícolas retangulares",
    "rio",
    "rotatória",
    "pista",
    "gelo do mar",
    "navio",
    "snowberg",
    "escasso residencial",
    "estádio",
    "reservatório de armazenamento",
    "quadra de tênis",
    "terraço",
    "central térmica",
    "wetland",
]


resisc45_templates = [
    "imagens de satélite de {}.",
    "imagens aéreas de {}.",
    "fotografia por satélite de {}.",
    "fotografia aérea de {}.",
    "vista por satélite de {}.",
    "vista aérea de {}.",
    "imagens de satélite de um {}.",
    "imagens aéreas de um {}.",
    "fotografia por satélite de um {}.",
    "fotografia aérea de um {}.",
    "vista por satélite de um {}.",
    "vista aérea de um {}.",
    "imagens de satélite do {}.",
    "imagens aéreas do {}.",
    "fotografia por satélite do {}.",
    "fotografia aérea do {}.",
    "vista por satélite do {}.",
    "vista aérea do {}.",
]


sst2_classes = [
    'negativo',
    'positivo',
]


sst2_templates = [
    "Uma avaliação {} de um filme",
]


stanfordcars_classes = [
    'Acura Integra Type R 2001',
    'Acura RL Sedan 2012',
    'Acura TL Sedan 2012',
    'Acura TL Type-S 2008',
    'Acura TSX Sedan 2012',
    'Acura ZDX Hatchback 2012',
    'AM General Hummer SUV 2000',
    'Aston Martin V8 Vantage Convertible 2012',
    'Aston Martin V8 Vantage Coupe 2012',
    'Aston Martin Virage Convertible 2012',
    'Aston Martin Virage Coupe 2012',
    'Audi 100 Sedan 1994',
    'Audi 100 Wagon 1994',
    'Audi A5 Coupe 2012',
    'Audi R8 Coupe 2012',
    'Audi RS 4 Convertible 2008',
    'Audi S4 Sedan 2007',
    'Audi S4 Sedan 2012',
    'Audi S5 Convertible 2012',
    'Audi S5 Coupe 2012',
    'Audi S6 Sedan 2011',
    'Audi TTS Coupe 2012',
    'Audi TT Hatchback 2011',
    'Audi TT RS Coupe 2012',
    'Audi V8 Sedan 1994',
    'Bentley Arnage Sedan 2009',
    'Bentley Continental Flying Spur Sedan 2007',
    'Bentley Continental GT Coupe 2007',
    'Bentley Continental GT Coupe 2012',
    'Bentley Continental Supersports Conv. Convertible 2012',
    'Bentley Mulsanne Sedan 2011',
    'BMW 1 Series Convertible 2012',
    'BMW 1 Series Coupe 2012',
    'BMW 3 Series Sedan 2012',
    'BMW 3 Series Wagon 2012',
    'BMW 6 Series Convertible 2007',
    'BMW ActiveHybrid 5 Sedan 2012',
    'BMW M3 Coupe 2012',
    'BMW M5 Sedan 2010',
    'BMW M6 Convertible 2010',
    'BMW X3 SUV 2012',
    'BMW X5 SUV 2007',
    'BMW X6 SUV 2012',
    'BMW Z4 Convertible 2012',
    'Bugatti Veyron 16.4 Convertible 2009',
    'Bugatti Veyron 16.4 Coupe 2009',
    'Buick Enclave SUV 2012',
    'Buick Rainier SUV 2007',
    'Buick Regal GS 2012',
    'Buick Verano Sedan 2012',
    'Cadillac CTS-V Sedan 2012',
    'Cadillac Escalade EXT Crew Cab 2007',
    'Cadillac SRX SUV 2012',
    'Chevrolet Avalanche Crew Cab 2012',
    'Chevrolet Camaro Convertible 2012',
    'Chevrolet Cobalt SS 2010',
    'Chevrolet Corvette Convertible 2012',
    'Chevrolet Corvette Ron Fellows Edition Z06 2007',
    'Chevrolet Corvette ZR1 2012',
    'Chevrolet Express Cargo Van 2007',
    'Chevrolet Express Van 2007',
    'Chevrolet HHR SS 2010',
    'Chevrolet Impala Sedan 2007',
    'Chevrolet Malibu Hybrid Sedan 2010',
    'Chevrolet Malibu Sedan 2007',
    'Chevrolet Monte Carlo Coupe 2007',
    'Chevrolet Silverado 1500 Classic Extended Cab 2007',
    'Chevrolet Silverado 1500 Extended Cab 2012',
    'Chevrolet Silverado 1500 Hybrid Crew Cab 2012',
    'Chevrolet Silverado 1500 Regular Cab 2012',
    'Chevrolet Silverado 2500HD Regular Cab 2012',
    'Chevrolet Sonic Sedan 2012',
    'Chevrolet Tahoe Hybrid SUV 2012',
    'Chevrolet TrailBlazer SS 2009',
    'Chevrolet Traverse SUV 2012',
    'Chrysler 300 SRT-8 2010',
    'Chrysler Aspen SUV 2009',
    'Chrysler Crossfire Convertible 2008',
    'Chrysler PT Cruiser Convertible 2008',
    'Chrysler Sebring Convertible 2010',
    'Chrysler Town and Country Minivan 2012',
    'Daewoo Nubira Wagon 2002',
    'Dodge Caliber Wagon 2007',
    'Dodge Caliber Wagon 2012',
    'Dodge Caravan Minivan 1997',
    'Dodge Challenger SRT8 2011',
    'Dodge Charger Sedan 2012',
    'Dodge Charger SRT-8 2009',
    'Dodge Dakota Club Cab 2007',
    'Dodge Dakota Crew Cab 2010',
    'Dodge Durango SUV 2007',
    'Dodge Durango SUV 2012',
    'Dodge Journey SUV 2012',
    'Dodge Magnum Wagon 2008',
    'Dodge Ram Pickup 3500 Crew Cab 2010',
    'Dodge Ram Pickup 3500 Quad Cab 2009',
    'Dodge Sprinter Cargo Van 2009',
    'Eagle Talon Hatchback 1998',
    'Ferrari 458 Italia Convertible 2012',
    'Ferrari 458 Italia Coupe 2012',
    'Ferrari California Convertible 2012',
    'Ferrari FF Coupe 2012',
    'FIAT 500 Abarth 2012',
    'FIAT 500 Convertible 2012',
    'Fisker Karma Sedan 2012',
    'Ford E-Series Wagon Van 2012',
    'Ford Edge SUV 2012',
    'Ford Expedition EL SUV 2009',
    'Ford F-150 Regular Cab 2007',
    'Ford F-150 Regular Cab 2012',
    'Ford F-450 Super Duty Crew Cab 2012',
    'Ford Fiesta Sedan 2012',
    'Ford Focus Sedan 2007',
    'Ford Freestar Minivan 2007',
    'Ford GT Coupe 2006',
    'Ford Mustang Convertible 2007',
    'Ford Ranger SuperCab 2011',
    'Geo Metro Convertible 1993',
    'GMC Acadia SUV 2012',
    'GMC Canyon Extended Cab 2012',
    'GMC Savana Van 2012',
    'GMC Terrain SUV 2012',
    'GMC Yukon Hybrid SUV 2012',
    'Honda Accord Coupe 2012',
    'Honda Accord Sedan 2012',
    'Honda Odyssey Minivan 2007',
    'Honda Odyssey Minivan 2012',
    'HUMMER H2 SUT Crew Cab 2009',
    'HUMMER H3T Crew Cab 2010',
    'Hyundai Accent Sedan 2012',
    'Hyundai Azera Sedan 2012',
    'Hyundai Elantra Sedan 2007',
    'Hyundai Elantra Touring Hatchback 2012',
    'Hyundai Genesis Sedan 2012',
    'Hyundai Santa Fe SUV 2012',
    'Hyundai Sonata Hybrid Sedan 2012',
    'Hyundai Sonata Sedan 2012',
    'Hyundai Tucson SUV 2012',
    'Hyundai Veloster Hatchback 2012',
    'Hyundai Veracruz SUV 2012',
    'Infiniti G Coupe IPL 2012',
    'Infiniti QX56 SUV 2011',
    'Isuzu Ascender SUV 2008',
    'Jaguar XK XKR 2012',
    'Jeep Compass SUV 2012',
    'Jeep Grand Cherokee SUV 2012',
    'Jeep Liberty SUV 2012',
    'Jeep Patriot SUV 2012',
    'Jeep Wrangler SUV 2012',
    'Lamborghini Aventador Coupe 2012',
    'Lamborghini Diablo Coupe 2001',
    'Lamborghini Gallardo LP 570-4 Superleggera 2012',
    'Lamborghini Reventon Coupe 2008',
    'Land Rover LR2 SUV 2012',
    'Land Rover Range Rover SUV 2012',
    'Lincoln Town Car Sedan 2011',
    'Maybach Landaulet Convertible 2012',
    'Mazda Tribute SUV 2011',
    'McLaren MP4-12C Coupe 2012',
    'Mercedes-Benz 300-Class Convertible 1993',
    'Mercedes-Benz C-Class Sedan 2012',
    'Mercedes-Benz E-Class Sedan 2012',
    'Mercedes-Benz S-Class Sedan 2012',
    'Mercedes-Benz SL-Class Coupe 2009',
    'Mercedes-Benz Sprinter Van 2012',
    'MINI Cooper Roadster Convertible 2012',
    'Mitsubishi Lancer Sedan 2012',
    'Nissan 240SX Coupe 1998',
    'Nissan Juke Hatchback 2012',
    'Nissan Leaf Hatchback 2012',
    'Nissan NV Passenger Van 2012',
    'Plymouth Neon Coupe 1999',
    'Porsche Panamera Sedan 2012',
    'Ram C V Cargo Van Minivan 2012',
    'Rolls-Royce Ghost Sedan 2012',
    'Rolls-Royce Phantom Drophead Coupe Convertible 2012',
    'Rolls-Royce Phantom Sedan 2012',
    'Scion xD Hatchback 2012',
    'smart fortwo Convertible 2012',
    'Spyker C8 Convertible 2009',
    'Spyker C8 Coupe 2009',
    'Suzuki Aerio Sedan 2007',
    'Suzuki Kizashi Sedan 2012',
    'Suzuki SX4 Hatchback 2012',
    'Suzuki SX4 Sedan 2012',
    'Tesla Model S Sedan 2012',
    'Toyota 4Runner SUV 2012',
    'Toyota Camry Sedan 2012',
    'Toyota Corolla Sedan 2012',
    'Toyota Sequoia SUV 2012',
    'Volkswagen Beetle Hatchback 2012',
    'Volkswagen Golf Hatchback 1991',
    'Volkswagen Golf Hatchback 2012',
    'Volvo 240 Sedan 1993',
    'Volvo C30 Hatchback 2012',
    'Volvo XC90 SUV 2007',
]


stanfordcars_templates = [
    "uma foto de um {}.",
    "uma foto do {}.",
    "uma foto do meu {}.",
    "Eu adoro o meu {}!",
    "Uma foto da minha {} suja.",
    "Uma foto da minha {} limpa.",
    "uma foto da minha nova {}.",
    "Uma foto da minha antiga {}.",
]


pascalvoc2007_classes = [
    "avião",
    "bicicleta",
    "pássaro",
    "barco",
    "frasco",
    "ônibus",
    "carro",
    "gato",
    "cadeira",
    "vaca",
    "mesa de jantar",
    "cão",
    "cavalo",
    "motocicleta",
    "pessoa",
    "planta de interior",
    "ovelha",
    "sofá",
    "trem",
    "monitor de tv",
]

pascalvoc2007_templates = [
    "Uma foto de um {}.",
]


class_map = {
    'gtsrb': gtsrb_classes,
    'cifar-10': cifar10_classes,
    'caltech-101': caltech101_classes,
    'cifar-100': cifar100_classes,
    'country211': country211_classes,
    'fgvc-aircraft-2013b-variants102': fgvcaircraft_classes,
    'oxford-flower-102': flowers102_classes,
    'food-101': food101_classes,
    'kitti-distance': kitti_classes,
    'mnist': mnist_classes,
    'patch-camelyon': patchcamelyon_classes,
    'resisc45_clip': resisc45_classes,
    'stanford-cars': stanfordcars_classes,
    'oxford-iiit-pets': oxfordpets_classes,
    'eurosat_clip': eurosat_classes,
    'hateful-memes': hatefulmemes_classes,
    'rendered-sst2': sst2_classes,
    'dtd': describabletextures_classes,
    'fer-2013': facialemotionrecognition2013_classes,
    'voc-2007-classification': pascalvoc2007_classes
}

template_map = {
    'gtsrb': gtsrb_templates,
    'cifar-10': cifar100_templates,
    'caltech-101': caltech101_templates,
    'cifar-100': cifar100_templates,
    'country211': country211_templates,
    'fgvc-aircraft-2013b-variants102': fgvcaircraft_templates,
    'oxford-flower-102': flowers102_templates,
    'food-101': food101_templates,
    'kitti-distance': kitti_templates,
    'mnist': mnist_templates,
    'patch-camelyon': patchcamelyon_templates,
    'resisc45_clip': resisc45_templates,
    'stanford-cars': stanfordcars_templates,
    'voc-2007-classification': pascalvoc2007_templates,
    'oxford-iiit-pets': oxfordpets_templates,
    'eurosat_clip': eurosat_templates,
    'hateful-memes': hatefulmemes_templates,
    'rendered-sst2': sst2_templates,
    'dtd': describabletextures_templates,
    'fer-2013': facialemotionrecognition2013_templates,
}