title: TEST_pracegover_OpenCLIP_Adapters_PEFT_1000-bs_filtered-dataset_no-proj

datasets:
    train:
        - name: pracegover
          path: "/hadatasets/clip_pt/final_webdatasets/pracegover_train_filtered/00000.tar"

    validation:
        - name: flickr30k
          path: "/hadatasets/clip_pt/final_webdatasets/flickr30k_val/00000.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

model:
    adapter: "LoRA"
    number_layers: 11
    progressive_adapter: -1

optimizer:
    name: "Adam"
    params:
        learning_rate: 1e-3
        eps: 1e-6
        weight_decay: 0.2
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 2

batch_size: 1000
accumulate_grad_batches: 1
tags:
    - Adapters
    - 5-Steps
    - Filtered-Dataset
    - 1000-BS
    
trainer:
    accelerator: "gpu"
    max_steps: 5  #
    num_sanity_val_steps: 0
    overfit_batches: 0.0
    log_every_n_steps: 1
    val_check_interval: 1

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/classification_loss/dataloader_idx_1"
    dirpath: "../checkpoints/clip_pt/MSCOCO_LiT"

early_stopping:
    verbose: true
    monitor: "val/classification_loss/dataloader_idx_1"
    patience: 100

carbon:
    carbon_checker: "false"
    brazil_carbon_intensity: 0.077
    process: "process"

