title: CC3M_LaCLIP_OpenCLIP_augument_caption_limit_${limit_num_captions}_${trainer.max_steps}_steps-${optimizer.params.min_learning_rate}-${optimizer.params.learning_rate}
tags:
    - text_augmentation
    - laclip

datasets:
    train:
        - name: CC3M_LaCLIP
          path: "/hadatasets/clip_pt/final_webdatasets/cc3m_laclip/{00000..00259}.tar"

    validation:
            #- name: pracegover
            #path: "/hadatasets/clip_pt/final_webdatasets/pracegover_val/{00000..00007}.tar"
        - name: flickr30k
          path: "/hadatasets/clip_pt/final_webdatasets/flickr30k_val/00000.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

augment: True
laclip: True
limit_num_captions: 4
optimizer:
    name: "Adam"
    params:
        learning_rate: 5e-7
        min_learning_rate: 1e-8
        eps: 1e-6
        weight_decay: 0.2
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 2500


batch_size: 2816
accumulate_grad_batches: 1

trainer:
    accelerator: "gpu"
    max_steps: 9220 # 10 epochs
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10
    val_check_interval: 100

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/retrieval_loss/dataloader_idx_0"
    dirpath: "../checkpoints/clip_pt/LaCLIP"

early_stopping:
    verbose: true
    monitor: "val/retrieval_loss/dataloader_idx_0"
    patience: 9220

carbon:
    carbon_checker: "false"
    brazil_carbon_intensity: 0.077
    process: "process"
