title: CC3M_self_distill_dynamic_alpha_1e-4

datasets:
    train:
        #- name: mscoco
        #  path: "/hadatasets/clip_pt/final_webdatasets/mscoco_train/{00000..00011}.tar"
        - name: CC3M
          path: "/hadatasets/clip_pt/final_webdatasets/cc3m-with-repetition/{00000..00266}.tar"

    validation:
        - name: pracegover
          path: "/hadatasets/clip_pt/final_webdatasets/pracegover_val/{00000..00007}.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

self_distill: True
alpha:
    max_alpha: 1.0e-4
    min_alpha: 0.0
    warmup_start: 200
    warmup_end: 500

optimizer:
    name: "Adam"
    params:
        learning_rate: 2e-6
        eps: 1e-6
        weight_decay: 0.2
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 800


batch_size: 2816
accumulate_grad_batches: 1
tags:
    - Knowledge Distill

trainer:
    accelerator: "gpu"
    max_steps: 500  #
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/classification_loss/dataloader_idx_1"
    dirpath: "../checkpoints/clip_pt/MSCOCO_LiT"

early_stopping:
    verbose: true
    monitor: "val/classification_loss/dataloader_idx_1"
    patience: 100

carbon:
    carbon_checker: "false"
    brazil_carbon_intensity: 0.077
    process: "process"
