title: CC3M_EN_generated_caption_pt_10_epoch
tags:
    - data_centric
    - captioning & filtering

generated_captions: "all"
lang: "en"

datasets:
    train:
        - name: CC3M
          path: "/hadatasets/clip_pt/final_webdatasets/cc3m_blip2_augment_translated_sim/{00000..00266}.tar"

    validation:
        - name: flickr30k # pracegover
          path: "/hadatasets/clip_pt/final_webdatasets/flickr30k_val/00000.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

augment: True
optimizer:
    name: "Adam"
    params:
        min_learning_rate: 1e-7
        learning_rate: 5e-7
        eps: 1e-8
        weight_decay: 0.2
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 500


batch_size: 2816
accumulate_grad_batches: 1

trainer:
    # gradient_clip_val: 1.0 # clip gradients' global norm to <= 1.0
    accelerator: "gpu"
    max_steps: 5863 # 10 epochs
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10
    val_check_interval: 100

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/retrieval_loss/dataloader_idx_0"
    dirpath: "../checkpoints/clip_pt/MSCOCO_LiT"

early_stopping:
    verbose: true
    monitor: "val/retrieval_loss/dataloader_idx_0"
    patience: 100

carbon:
    carbon_checker: "false"
    brazil_carbon_intensity: 0.077
    process: "process"
