title: mscoco_teacher_student

datasets:
    train:
        - name: mscoco
          path: "/hadatasets/clip_pt/final_webdatasets/mscoco_train/{00000..00011}.tar"

    validation:
        - name: mscoco
          path: "/hadatasets/clip_pt/final_webdatasets/mscoco_val/00000.tar"

model:
    teacher: "openai/clip-vit-base-patch32"
    student: "neuralmind/bert-base-portuguese-cased"
    text_padding_size: 95

optimizer:
    name: "Adam"
    params:
        learning_rate: 1e-4
        eps: 1e-8
        weight_decay: 0.1
        betas: [ 0.99, 0.999 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 800


batch_size: 2816
accumulate_grad_batches: 1

trainer:
    accelerator: "gpu"
    max_epochs: 20  #
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/loss"
    dirpath: "../checkpoints/clip_pt/mscoco_teacher_student"

carbon:
    brazil_carbon_intensity: 0.077
    process: "process"
