title: MSCOCO_BERT_Large_AugMix_LiT_LoRA_linear_1000steps_alpha-16_progressive

datasets:
    train:
        - name: mscoco
          path: "/hadatasets/clip_pt/final_webdatasets/mscoco_train/{00000..00011}.tar"

    validation:
        - name: pracegover
          path: "/hadatasets/clip_pt/final_webdatasets/pracegover_val/{00000..00007}.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

augment: AugMix

model:
    text_encoder: "neuralmind/bert-large-portuguese-cased"
    image_encoder: "openai/clip-vit-base-patch32"
    text_padding_size: 95
    number_layers: 24
    warmup_steps: 1e9 # keeps the image encoder for the whole training
    pretraining: "LiT" #options: LiT / contrascurtive
    adapter: "LoRA"
    progressive_adapter: 20

optimizer:
    name: "Adam"
    params:
        learning_rate: 1e-3
        eps: 1e-6
        weight_decay: 0.001
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "LinearLR"
    params:
        start_factor: 1.0
        end_factor: 0.1
        total_iters: 1000

batch_size: 1816
accumulate_grad_batches: 1

trainer:
    accelerator: "gpu"
    max_epochs: 20  #
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/classification_loss/dataloader_idx_1"
    dirpath: "../checkpoints/clip_pt/MSCOCO_LiT"

early_stopping:
    verbose: true
    monitor: "val/classification_loss/dataloader_idx_1"
    patience: 100

carbon:
    carbon_checker: "false"
    brazil_carbon_intensity: 0.077
    process: "process"