title: MSCOCO_OpenCLIP_filtered_positive

datasets:
    train:
        - name: mscoco-filtered-positive
          path: "/hadatasets/clip_pt/final_webdatasets/mscoco_train_filtered_positive/{00000..00007}.tar"

    validation:
            #- name: pracegover
            # path: "/hadatasets/clip_pt/final_webdatasets/pracegover_val/{00000..00007}.tar"
        - name: flickr30k
          path: "/hadatasets/clip_pt/final_webdatasets/flickr30k_val/00000.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

optimizer:
    name: "Adam"
    params:
        learning_rate: 1e-5
        eps: 1e-6
        weight_decay: 0.2
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 800


batch_size: 2816
accumulate_grad_batches: 1

trainer:
    accelerator: "gpu"
    max_epochs: 20  #
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/classification_loss/dataloader_idx_1"
    dirpath: "../checkpoints/clip_pt/MSCOCO_LiT"

early_stopping:
    verbose: true
    monitor: "val/classification_loss/dataloader_idx_1"
    patience: 100

carbon:
    brazil_carbon_intensity: 0.077
    process: "process"
