title: PraCegoVer_CC3M_filtered_OpenCLIP
tags:
    - data_centric
    -
datasets:
    train:
        - name: pracegover-filtered
          path: "/hadatasets/clip_pt/final_webdatasets/pracegover_train_filtered/{00000..00018}.tar"
        - name: CC3M-filtered
          path: "/hadatasets/clip_pt/final_webdatasets/cc3m_filtered/{00000..00165}.tar"

    validation:
        - name: flickr30k # pracegover
          path: "/hadatasets/clip_pt/final_webdatasets/flickr30k_val/00000.tar"

    img_classification:
        path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/val.txt"
        annotation_path: "/hadatasets/clip_pt/validation_datasets/GroceryStoreDataset/dataset/translated_classes_gsd.csv"

augment: True
optimizer:
    name: "Adam"
    params:
        learning_rate: 2e-6
        eps: 1e-6
        weight_decay: 0.2
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "CosineWarmupLR"
    params:
        warmup_lr: 250


batch_size: 2816
accumulate_grad_batches: 1

trainer:
    accelerator: "gpu"
    max_steps: 700
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10
    val_check_interval: 100
    check_val_every_n_epoch:

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/retrieval_loss/dataloader_idx_0"
    dirpath: "../checkpoints/clip_pt/MSCOCO_LiT"

early_stopping:
    verbose: true
    monitor: "val/retrieval_loss/dataloader_idx_0"
    patience: 100

carbon:
    carbon_checker: "false"
    brazil_carbon_intensity: 0.077
    process: "process"
