title: ReduceLROnPlateau_1e-4

datasets:
    train:
        - name: pracegover
          path: "/hadatasets/pracegover/{00000..00403}.tar"

    validation:
        - name: pracegover
          path: "/hadatasets/pracegover/{00000..00403}.tar"

model:
    text_encoder: "neuralmind/bert-base-portuguese-cased"
    image_encoder: "openai/clip-vit-base-patch32"
    text_padding_size: 95
    warmup_steps: 1000
    pretraining: "LiT" #options: LiT / contrastive

optimizer:
    name: "Adam"
    params:
        learning_rate: 1e-4
        eps: 1e-6
        weight_decay: 0.001
        betas: [ 0.9, 0.98 ]

scheduler:
    name: "ReduceLROnPlateau"
    params:
        patience: 200 # about 2 epochs on PraCegoVer 403k


batch_size: 2816
accumulate_grad_batches: 1

trainer:
    accelerator: "gpu"
    max_epochs: 20  #
    num_sanity_val_steps: 2
    overfit_batches: 0.0
    log_every_n_steps: 10

model_checkpoint:
    mode: "min"
    save_last: true
    save_weights_only: true
    monitor: "val/loss"
    dirpath: "../checkpoints/clip_pt/reduceLROnPlateau_1e-4"

early_stopping:
    verbose: true
    monitor: "val/loss"
    patience: 100

